# Generated by Django 4.1.1 on 2023-05-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_room_remove_video_uploaded_by_delete_audio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
