# Generated by Django 4.1.1 on 2023-12-30 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_room', '0003_alter_message_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.localtime, editable=False),
        ),
    ]
