# Generated by Django 4.1.1 on 2023-12-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_room', '0005_alter_message_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date_added',
            new_name='timestamp',
        ),
    ]
