# Generated by Django 4.1.1 on 2024-01-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_room', '0009_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='msg_time',
            new_name='timestamp',
        ),
    ]
